### ISSUE TITLE
can't open the pokemon storage

### ISSUE THREAD

**Issue by thenerdikon** [wanhose/pokemon-reminiscencia-linux#1]
hey!

thanks for the great tutorial! i just have a short question since i seem unable to open the pokemon bag/ teleport on map where i need to usually press T on the keyboard. may i ask how you solved the issue?

**Comment by wanhose** [comment]
Hey @thenerdikon,

Glad it helped you! Have you tried changing or checking your keyboard layout by pressing the F1 key in-game?
